name = "opiumstore-api"
main = "src/index.js"
compatibility_date = "2026-07-12"

[vars]
DISCORD_ADMIN_ROLE_ID = "1518913320831160431"
VAPID_SUBJECT = "mailto:opiumstoregen@gmail.com"
VAPID_PUBLIC_KEY = "BLZpn6bV4Tb7-4U8_u6IV4_VUx6t7tG2vOUSFTpSmL6-uxjZUVv3Ac6rqthN4ID_o3YNaWraK30hfcEhWHpfRqQ"
DISCORD_CLIENT_ROLE_ID = "1518913330914529380"
DISCORD_VIP_ROLE_ID = "1521067390199136306"
DISCORD_BOOST_ROLE_ID = "1521817444019208284"
DISCORD_GUILD_ID = "1518911579817509015"
FRONTEND_ORIGIN = "https://opiumstore-hub.onrender.com"
DISCORD_REDIRECT_URI = "https://opiumstore-api.opiumstore.workers.dev/auth/discord/callback"
ADMIN_DISCORD_IDS = "1456328839062880409"

[[d1_databases]]
binding = "DB"
database_name = "opiumstore-db"
database_id = "1ccf6b9b-d1ab-40a1-81d6-6d2c9dfd4b59"

[triggers]
crons = ["*/30 * * * *"]
